# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: yarn install
    - run: yarn start
    - name: Publish to npmjs
    - run: yarn publish --non-interactive
      env:
       NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Publish to GitHub Packages
    - run: yarn publish --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
