# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm publish

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Publish to GitHub Packages
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        registry-url: "https://npm.pkg.github.com/"
        scope: "@aicevote"
    - run: cat ~/.npmrc
    - run: yarn install
    - run: yarn build
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to npm Public Packages
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        registry-url: "https://registry.npmjs.org"
    - run: cat ~/.npmrc
    - run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
